version: "3"
services:
    emqt:
        build: ./
        image: emq
        container_name: emq
        restart: always
        environment:
            - EMQ_LOADED_PLUGINS="emq_dashboard,emq_auth_http"
        logging:
            driver: "json-file"
            options:
                max-size: "200m"
                max-file: "10"
        ports:
            - "0.0.0.0:1883:1883"
            - "0.0.0.0:8083:8083"
            - "0.0.0.0:8084:8084"
            - "0.0.0.0:8883:8883"
            - "0.0.0.0:18083:18083"
            - "0.0.0.0:4369:4369"
            - "0.0.0.0:6000-6100:6000-6100"